ExpenseTracker/Controllers/ExpenseController.cs
using AutoMapper;
using ExpenseTracker.BLL;
using ExpenseTracker.BLL.Interfaces;
using ExpenseTracker.BLL.Specifications;
using ExpenseTracker.DAL.Models;
using ExpenseTracker.PL.ViewModels;
using ExpenseTracker.PL.ViewSpecifications;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.PL.Controllers
{
    public class ExpenseController : BaseController
    {

        public ExpenseController(IMapper mapper, IUnitOfWork unitOfWork) : base(mapper, unitOfWork)
        {
        }
        public async Task<ActionResult < Pagination<Expense> > > Index(ExpenseSpecifications spec)
        {

            var FilterSpecifications = new FilteredExpenseSpecifications(spec.MinAmount , spec.MaxAmount , spec.MinDate , spec.MaxDate , spec.Category , spec.AccountName , spec.PageIndex);

            var Expenses = await _UnitOfWork.ExpenseRepository.GetAllAsyncWithSpec(FilterSpecifications) as IReadOnlyList<Expense>;

            var Count = await _UnitOfWork.ExpenseRepository.GetCountAsync(FilterSpecifications);

            return View(new Pagination<Expense>() {Items = Expenses , Count = Count , PageNo = spec.PageIndex , PageSize = spec.PageSize});
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExpenseViewModel expense)
        {
            if (ModelState.IsValid)
            {
                var MappedExpense = _Mapper.Map<ExpenseViewModel, Expense>(expense);

                


                await _UnitOfWork.ExpenseRepository.AddAsync(MappedExpense);

                var count = await _UnitOfWork.CompleteAsync();



                if (count > 0)
                    return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {

            if(id is null) return BadRequest();

            var Expense = _UnitOfWork.ExpenseRepository.GetAsync(id.Value).Result;

            TempData["ExpenseId"] = (int)Expense.Id;

            var MappedExpense = _Mapper.Map<Expense, ExpenseViewModel>(Expense);

            return View(MappedExpense);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExpenseViewModel expense)
        {

            if (ModelState.IsValid)
            {
                var MappedExpense = _Mapper.Map<ExpenseViewModel, Expense>(expense);

                MappedExpense.Id = (int)TempData["ExpenseId"];



                await _UnitOfWork.ExpenseRepository.UpdateAsync(MappedExpense);



                var Count = await _UnitOfWork.CompleteAsync();
                
                if(Count > 0)return RedirectToAction(nameof(Index));

                else return View(expense);
            }

            return View(expense);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return BadRequest();

            var Expense = await _UnitOfWork.ExpenseRepository.GetAsync(id.Value);

            var MappedExpense = _Mapper.Map<Expense, ExpenseViewModel>(Expense);

            if (Expense is null) return NotFound();

            return View(MappedExpense);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return BadRequest();
            
            var Expense = await _UnitOfWork.ExpenseRepository.GetAsync(id.Value);
            
            if (Expense is null) return NotFound();

            await _UnitOfWork.ExpenseRepository.DeleteAsync(Expense);
            
            var Count = await _UnitOfWork.CompleteAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

ExpenseTracker/Controllers/IncomeController.cs
using AutoMapper;
using ExpenseTracker.BLL;
using ExpenseTracker.BLL.Interfaces;
using ExpenseTracker.BLL.Specifications;
using ExpenseTracker.DAL.Models;
using ExpenseTracker.PL.ViewModels;
using ExpenseTracker.PL.ViewSpecifications;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.PL.Controllers
{
    public class IncomeController : BaseController
    {

        public IncomeController(IMapper mapper, IUnitOfWork unitOfWork) : base(mapper, unitOfWork)
        {
        }

        public async Task<ActionResult<Pagination<Income> > > Index(IncomeSpecifications spec)
        {

            var FilterSpecifications = new FilteredIncomeSpecifications(spec.MinAmount , spec.MaxAmount , spec.MinDate , spec.MaxDate , spec.AccountName , spec.PageIndex);

            var Incomes = await _UnitOfWork.IncomeRepository.GetAllAsyncWithSpec(FilterSpecifications) as IReadOnlyList<Income>;

            var Count = await _UnitOfWork.IncomeRepository.GetCountAsync(FilterSpecifications);

            return View(new Pagination<Income>() {Items = Incomes , Count = Count , PageNo = spec.PageIndex , PageSize = spec.PageSize});
        }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(IncomeViewModel income)
        {
            if (ModelState.IsValid)
            {
                var MappedIncome = _Mapper.Map<IncomeViewModel , Income>(income);

                await _UnitOfWork.IncomeRepository.AddAsync(MappedIncome);
                
                var Count = await _UnitOfWork.CompleteAsync();
                


                if(Count > 0)return RedirectToAction(nameof(Index));

                return View(income);
            }
            return View(income);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if(id is null)return BadRequest();

            var Income = await _UnitOfWork.IncomeRepository.GetAsync(id.Value);

            TempData["Id"] = id.Value;

            var MappedIncome = _Mapper.Map<Income, IncomeViewModel>(Income);

            return View(MappedIncome);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IncomeViewModel income)
        {
            if (ModelState.IsValid)
            {
                var MappedExpense = _Mapper.Map<IncomeViewModel, Income>(income);

                MappedExpense.Id = (int)TempData["Id"];

                await _UnitOfWork.IncomeRepository.UpdateAsync(MappedExpense);

                var Count = await _UnitOfWork.CompleteAsync();

                if(Count > 0) return RedirectToAction(nameof(Index));
                else return(View(income));
            }
            return View(income);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return BadRequest();


            var Income = await _UnitOfWork.IncomeRepository.GetAsync(id.Value);

            var MappedIncome = _Mapper.Map<Income, IncomeViewModel>(Income);


            return View(MappedIncome);
        }

        public async Task<IActionResult> Delete(int? id)
        {

            if(id is null) return BadRequest();

            var Income = await _UnitOfWork.IncomeRepository.GetAsync(id.Value);

            await _UnitOfWork.IncomeRepository.DeleteAsync(Income);

            await _UnitOfWork.CompleteAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

ExpenseTracker/Controllers/TransferController.cs
using AutoMapper;
using ExpenseTracker.BLL;
using ExpenseTracker.BLL.Interfaces;
using ExpenseTracker.BLL.Specifications;
using ExpenseTracker.DAL.Models;
using ExpenseTracker.PL.ViewModels;
using ExpenseTracker.PL.ViewSpecifications;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.PL.Controllers
{
    public class TransferController : BaseController
    {

        public TransferController(IMapper mapper, IUnitOfWork unitOfWork) : base(mapper, unitOfWork)
        {
        }

        public async Task<ActionResult<Pagination<Transfer> > > Index(TransferSpecifications spec)
        {
            var FilterSpecifications = new FilteredTransferSpecifications(spec.SourceAccountName , spec.RecipientAccountName , spec.MinAmount , spec.MaxAmount , spec.MinDate ,spec.MaxDate ,spec.PageIndex);

            var Transfers = await _UnitOfWork.TransferRepository.GetAllAsyncWithSpec(FilterSpecifications) as IReadOnlyList<Transfer>;

            var Count = await _UnitOfWork.TransferRepository.GetCountAsync(FilterSpecifications);

            return View(new Pagination<Transfer>(){Items = Transfers , Count = Count , PageNo = spec.PageIndex , PageSize = spec.PageSize });
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransferViewModel transfer)
        {

            if (ModelState.IsValid)
            {
                var MappedTransfer = _Mapper.Map<TransferViewModel,Transfer>(transfer);

                await _UnitOfWork.TransferRepository.AddAsync(MappedTransfer);

                var Count = await _UnitOfWork.CompleteAsync();

                if (Count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else return View(transfer);
            }
            return View(transfer);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id is null) return NotFound();

            TempData["Id"] = id.Value;

            var Transfer = await _UnitOfWork.TransferRepository.GetAsync(id.Value);

            if (Transfer is null) return NotFound();

            var MappedTransfer = _Mapper.Map<Transfer, TransferViewModel>(Transfer);


            return View(MappedTransfer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TransferViewModel transfer)
        {
            if (ModelState.IsValid)
            {
                var MappedTransfer = _Mapper.Map<TransferViewModel, Transfer>(transfer);

                MappedTransfer.Id =(int) TempData["Id"];

                await _UnitOfWork.TransferRepository.UpdateAsync(MappedTransfer);

                var Count = await _UnitOfWork.CompleteAsync();
                if (Count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else return View(transfer);
            }
            return View(transfer);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return BadRequest();

            var Transfer = await _UnitOfWork.TransferRepository.GetAsync(id.Value);

            var MappedTransfer = _Mapper.Map<Transfer, TransferViewModel>(Transfer);

            if(Transfer is null) return NotFound();

            return View(MappedTransfer);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return NotFound();
            
            var Transfer = await _UnitOfWork.TransferRepository.GetAsync(id.Value);
            
            if (Transfer is null) return NotFound();
            
            await _UnitOfWork.TransferRepository.DeleteAsync(Transfer);
             
            await _UnitOfWork.CompleteAsync();
             
            return RedirectToAction(nameof(Index));
            
            
        }

    }
}

ExpenseTracker/Views/Shared/_BudgetResetDateUpdate.cshtml
<script>
    function updateBudgets() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("CheckDate", "Budget")',
            dataType: "json",
            success: function (data) {
                console.log("Dates Updated Successfully");
            },
            error: function (xhr, status, error) {
                console.error("Error updating budgets: " + error);
            }
        });
        // Store the last run time
        localStorage.setItem('lastBudgetUpdate', Date.now());
    }

    $(document).ready(function () {
        function checkAndUpdateBudgets() {
            var lastRun = parseInt(localStorage.getItem('lastBudgetUpdate') || "0", 10);
            var now = Date.now();
            if (now - lastRun >= 60 * 1000) { // 1 minute
                updateBudgets();
            }
        }
        // Check immediately on page load
        checkAndUpdateBudgets();
        // Then check every 10 seconds (or any short interval)
        setInterval(checkAndUpdateBudgets, 10 * 1000);
    });
</script>

ExpenseTracker/Views/Shared/_Layout.cshtml
@using ExpenseTracker.BLL.Specifications
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Expense Tracker</title>

    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

</head>
<body>
    <header>
        <nav class="navbar-style">


            <div class="container-fluid">

                

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-layout">
                        

                        <li class="navitem">
                            <a class="navbar-button" asp-controller="Account" asp-action="Index">Accounts</a>
                        </li>

                        <li class="navitem">
                            <a class="navbar-button" asp-controller="Budget" asp-action="Index">Budgets</a>
                        </li>

                        <li class="navitem">
                            <a class="navbar-button" asp-controller="Expense" asp-action="Index">Expenses</a>
                        </li>

                        <li class="navitem">
                            <a class="navbar-button" asp-controller="Transfer" asp-action="Index">Transfers</a>
                        </li>

                        <li class="navitem">
                            <a class="navbar-button" asp-controller="Income" asp-action="Index">Income</a>
                        </li>

                    </ul>
                </div>


            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_BudgetResetDateUpdate" />



    @await RenderSectionAsync("Jquery", required: false)
    @await RenderSectionAsync("JqueryMultipleSelect", required: false)
    @await RenderSectionAsync("MultipleSelect", required: false)
    
    @await RenderSectionAsync("PeriodScript",required: false)
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("TransferScript", required: false)
    @await RenderSectionAsync("SetDateOnSubmission" , required: false)
</body>
</html>